### ISSUE TITLE
Making some kind of thousand separator

### ISSUE THREAD

**Issue by tcarlsen** [tcarlsen/caravanwar.info#6]
We have a lot of numbers on the website, and it can be hard to read all the big numbers. but Github pages dont allow custom plugins so we have to find a other way to make a thousand separator.

**Comment by tcarlsen** [comment]
any ideas @markovandooren

**Comment by markovandooren** [comment]
You should be able to use any javascript I think.

var number = 123456789;
number.toLocaleString(); // for local locale
number.toLocaleString('en-US'); // for a specific locale.

**Comment by tcarlsen** [comment]
I dont like having javascript doing a lot of dom changes. Will make the website to slow. We need to find a way to do it on build.

I tried using the replace filter like so: `{{ number | replace: /^(?!0+\.00)(?=.{1,9}(\.|$))\d{1,3}(,\d{3})*(\.\d+)?$/ }}`
